### ISSUE TITLE
onItemSelectedListener

### ISSUE THREAD

**Issue by Hoossayn** [Mamoon-Alhawamdeh/Amazing_Spinner#2]
somehow can't use onItemSelectedListener with this library

**Comment by Mamoon-Alhawamdeh** [comment]
Thank you for using AmazingSpinner, you can use setOnItemClickListener instead of onItemSelectedListener.

**Comment by Hoossayn** [comment]
What is the equivalent of  `seletedItem ` (getSelectedItem()) in the normal spinner

**Comment by Mamoon-Alhawamdeh** [comment]
You can save the selected value lik this 
YOURAMAZINGSPINNER.setOnItemClickListener(new AdapterView.OnItemClickListener() {

        @Override
        public void onItemClick(AdapterView<?> arg0, View arg1, int arg2,
                                long arg3) {
            Purpose selected = (Purpose) arg0.getItemAtPosition(arg2);
        }
    });


Or you can use :
YOUAMAZINGSPINNER.getText().toString()

**Comment by Hoossayn** [comment]
This is not giving me what i'm trying to achieve. i'm  using the spinner with a custom object say with values ID and NAME,  
1. I'll be showing the the NAME when each item is selected, so getText.toString() just return the name
2.  but i need the ID to make a network call, and i can't display the ID when the when each item is selected 

from the your code snippet, i can't cast type string to a Custom Object

**Comment by Mamoon-Alhawamdeh** [comment]
YOURAMAZINGSPINNER.setOnItemClickListener(new AdapterView.OnItemClickListener() {

    @Override
    public void onItemClick(AdapterView<?> arg0, View arg1, int arg2,
                            long arg3) {
        Purpose selected = (Purpose) arg0.getItemAtPosition(arg2);
    }
});``

**Comment by Hoossayn** [comment]
`  spinner.onItemClickListener =
            AdapterView.OnItemClickListener { parent, view, position, id ->
                val selectedObject: VehicleTypes? = parent?.getItemAtPosition(position) as? VehicleTypes
                // when(parent.selectedItem)
                Toast.makeText(requireContext(), selectedObject!!.id, Toast.LENGTH_SHORT).show()
            }`

selected object is null
