### ISSUE TITLE
Unable Hide the List properly when spinner is clicked

### ISSUE THREAD

**Issue by ArmandDitto** [Mamoon-Alhawamdeh/Amazing_Spinner#3]
When i clicked arrow icon, the spinner can show and hide the list properly. But once i clicked the area outside arrow icon it only show the list but cant hide it, so i should use arrow icon to hide menu.

Luckily i just found the solution. Just add onClickListener in your spinner to make area outside arrow icon can show/hide the list, like this. 
amazingSpinner.setOnClickListener {  }

Hope this will be helpful for someone who got the same issue,
Thanks.

**Comment by Mamoon-Alhawamdeh** [comment]
sorry for late and thank you for using AmazingSpinner, please find the updated version with fixed you issue.
